In [1]:
import pandas as pd
data=pd.read_csv("spam.csv")

In [2]:
data.head(100)

Category                                            Message
0       ham  Go until jurong point, crazy.. Available only ...
1       ham                      Ok lar... Joking wif u oni...
2      spam  Free entry in 2 a wkly comp to win FA Cup fina...
3       ham  U dun say so early hor... U c already then say...
4       ham  Nah I don't think he goes to usf, he lives aro...
..      ...                                                ...
95     spam  Your free ringtone is waiting to be collected....
96      ham                  Watching telugu movie..wat abt u?
97      ham  i see. When we finish we have loads of loans t...
98      ham  Hi. Wk been ok - on hols now! Yes on for a bit...
99      ham                    I see a cup of coffee animation

[100 rows x 2 columns]

In [3]:
data.Category.value_counts()

ham     4825
spam     747
Name: Category, dtype: int64

In [4]:
data["spam"]=data["Category"].apply(lambda x: 1 if x=="spam" else 0)

In [5]:
data.head()

Category                                            Message  spam
0      ham  Go until jurong point, crazy.. Available only ...     0
1      ham                      Ok lar... Joking wif u oni...     0
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...     1
3      ham  U dun say so early hor... U c already then say...     0
4      ham  Nah I don't think he goes to usf, he lives aro...     0

In [6]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(data["Message"],data["spam"],train_size=0.8,test_size=0.2,random_state=120)

C:\Users\rashi\anaconda\lib\site-packages\scipy\__init__.py:155: UserWarning: A NumPy version >=1.18.5 and <1.25.0 is required for this version of SciPy (detected version 1.26.4
  warnings.warn(f"A NumPy version >={np_minversion} and <{np_maxversion}"


In [7]:
print(f"{X_train.size} | {X_test.size}")

4457 | 1115


In [8]:
type(X_train)

pandas.core.series.Series

In [9]:
X_train[:4]

4293                                                G.W.R
3339              K, if u bored up just come to my home..
4721    Forgot to tell ü smth.. Can ü like number the ...
4538           Normally i use to drink more water daily:)
Name: Message, dtype: object

In [10]:
y_train[:4]

4293    0
3339    0
4721    0
4538    0
Name: spam, dtype: int64

In [11]:
from  sklearn.feature_extraction.text import CountVectorizer
#this will help us to get bag of words 
#this will get a collection of text documents to a matrix of token count
vec=CountVectorizer()
X_train_cv=vec.fit_transform(X_train)#here i could have used X_train.values could mean the same
X_train_cv

<4457x7841 sparse matrix of type '<class 'numpy.int64'>'
	with 59493 stored elements in Compressed Sparse Row format>

In [12]:
X_train_cv.toarray()[:50]

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [13]:
X_train_cv.shape
# that means we have 7841 total words in X_train documentation

(4457, 7841)

In [14]:
vec.get_feature_names_out()[1000:1050]

array(['antelope', 'antha', 'anthony', 'anti', 'any', 'anybody', 'anyhow',
       'anymore', 'anyone', 'anyones', 'anyplaces', 'anythiing',
       'anythin', 'anything', 'anythingtomorrow', 'anytime', 'anyway',
       'anyways', 'anywhere', 'aom', 'apart', 'apartment', 'apes',
       'apeshit', 'aphex', 'apnt', 'apo', 'apologetic', 'apologise',
       'apologize', 'apology', 'app', 'apparently', 'appeal', 'appear',
       'applausestore', 'applebees', 'apples', 'application', 'apply',
       'applyed', 'applying', 'appointment', 'appointments', 'appreciate',
       'appreciated', 'approaching', 'approve', 'apps', 'appt'],
      dtype=object)

In [15]:
vec.get_feature_names_out().shape
#this will get us the total no. of words contained in a document

(7841,)

In [16]:
vec.get_feature_names()

C:\Users\rashi\anaconda\lib\site-packages\sklearn\utils\deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)


['00',
 '000',
 '000pes',
 '008704050406',
 '0089',
 '0121',
 '01223585236',
 '01223585334',
 '02',
 '0207',
 '02072069400',
 '02073162414',
 '02085076972',
 '021',
 '03',
 '04',
 '05',
 '050703',
 '0578',
 '06',
 '07',
 '07008009200',
 '07046744435',
 '07090201529',
 '07090298926',
 '07099833605',
 '07123456789',
 '0721072',
 '07734396839',
 '07742676969',
 '07781482378',
 '077xxx',
 '078',
 '07801543489',
 '07808',
 '07808247860',
 '07815296484',
 '07821230901',
 '078498',
 '0796xxxxxx',
 '07xxxxxxxxx',
 '08',
 '0800',
 '08000407165',
 '08000776320',
 '08000839402',
 '08000930705',
 '08000938767',
 '08001950382',
 '08002888812',
 '08002986030',
 '08002986906',
 '08002988890',
 '08006344447',
 '0808',
 '08081263000',
 '0825',
 '083',
 '0844',
 '08448350055',
 '08448714184',
 '0845',
 '08450542832',
 '08452810071',
 '08452810073',
 '08452810075over18',
 '0870',
 '08700435505150p',
 '08700621170150p',
 '08701237397',
 '08701417012',
 '08701417012150p',
 '0870141701216',
 '08701752560',


In [17]:
#through this command we can get all the function and operation we could use 
dir(vec)

['__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__setstate__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_char_ngrams',
 '_char_wb_ngrams',
 '_check_feature_names',
 '_check_n_features',
 '_check_stop_words_consistency',
 '_check_vocabulary',
 '_count_vocab',
 '_get_param_names',
 '_get_tags',
 '_limit_features',
 '_more_tags',
 '_repr_html_',
 '_repr_html_inner',
 '_repr_mimebundle_',
 '_sort_features',
 '_stop_words_id',
 '_validate_data',
 '_validate_params',
 '_validate_vocabulary',
 '_warn_for_unused_params',
 '_white_spaces',
 '_word_ngrams',
 'analyzer',
 'binary',
 'build_analyzer',
 'build_preprocessor',
 'build_tokenizer',
 'decode',
 'decode_error',
 'dtype',
 'encoding',
 'fit',

In [18]:
vec.vocabulary_

{'if': 3630,
 'bored': 1455,
 'up': 7276,
 'just': 3916,
 'come': 1922,
 'to': 7020,
 'my': 4697,
 'home': 3509,
 'forgot': 2978,
 'tell': 6833,
 'smth': 6340,
 'can': 1647,
 'like': 4151,
 'number': 4890,
 'the': 6894,
 'sections': 6046,
 'so': 6354,
 'that': 6890,
 'it': 3792,
 'clearer': 1860,
 'normally': 4855,
 'use': 7311,
 'drink': 2469,
 'more': 4620,
 'water': 7491,
 'daily': 2163,
 'know': 4003,
 'complain': 1942,
 'num': 4889,
 'only': 4983,
 'bettr': 1356,
 'directly': 2355,
 'go': 3184,
 'bsnl': 1557,
 'offc': 4931,
 'nd': 4747,
 'apply': 1039,
 'for': 2967,
 'do': 2391,
 'noe': 4833,
 'wat': 7484,
 'time': 6985,
 'place': 5271,
 'dat': 2187,
 'sells': 6069,
 '4d': 502,
 'closes': 1872,
 'meeting': 4467,
 'is': 3781,
 'work': 7684,
 'tel': 6829,
 'me': 4448,
 'when': 7572,
 'shall': 6128,
 'tomorrow': 7046,
 'you': 7803,
 'are': 1062,
 'right': 5839,
 'meanwhile': 4456,
 'how': 3558,
 'project': 5497,
 'twins': 7180,
 'comin': 1927,
 'imagine': 3648,
 'finally': 2879,
 'ge

In [19]:
X_train_np=X_train_cv.toarray()
X_train_np[0]

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [20]:
import numpy as np
np.where(X_train_np[0]!=0)

(array([], dtype=int64),)

In [21]:
X_train[1579 ]

"How to Make a girl Happy? It's not at all difficult to make girls happy. U only need to be... 1. A friend 2. Companion 3. Lover 4. Chef . . .  &lt;#&gt; . Good listener  &lt;#&gt; . Organizer  &lt;#&gt; . Good boyfriend  &lt;#&gt; . Very clean  &lt;#&gt; . Sympathetic  &lt;#&gt; . Athletic  &lt;#&gt; . Warm . . .  &lt;#&gt; . Courageous  &lt;#&gt; . Determined  &lt;#&gt; . True  &lt;#&gt; . Dependable  &lt;#&gt; . Intelligent . . .  &lt;#&gt; . Psychologist  &lt;#&gt; . Pest exterminator  &lt;#&gt; . Psychiatrist  &lt;#&gt; . Healer . .  &lt;#&gt; . Stylist  &lt;#&gt; . Driver . . Aaniye pudunga venaam.."

In [24]:
# type(X_train)
type(X_train.values)


numpy.ndarray

In [27]:
from sklearn.feature_extraction.text import CountVectorizer
v= CountVectorizer()
X_train_cv=v.fit_transform(X_train.values)
X_train_cv

<4457x7841 sparse matrix of type '<class 'numpy.int64'>'
	with 59493 stored elements in Compressed Sparse Row format>

In [31]:
X_train_cv.toarray()[:2]

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [33]:
X_train_cv.shape
# 7841 this many no. of words are there in  the mails  

(4457, 7841)

In [37]:
v.get_feature_names()

['00',
 '000',
 '000pes',
 '008704050406',
 '0089',
 '0121',
 '01223585236',
 '01223585334',
 '02',
 '0207',
 '02072069400',
 '02073162414',
 '02085076972',
 '021',
 '03',
 '04',
 '05',
 '050703',
 '0578',
 '06',
 '07',
 '07008009200',
 '07046744435',
 '07090201529',
 '07090298926',
 '07099833605',
 '07123456789',
 '0721072',
 '07734396839',
 '07742676969',
 '07781482378',
 '077xxx',
 '078',
 '07801543489',
 '07808',
 '07808247860',
 '07815296484',
 '07821230901',
 '078498',
 '0796xxxxxx',
 '07xxxxxxxxx',
 '08',
 '0800',
 '08000407165',
 '08000776320',
 '08000839402',
 '08000930705',
 '08000938767',
 '08001950382',
 '08002888812',
 '08002986030',
 '08002986906',
 '08002988890',
 '08006344447',
 '0808',
 '08081263000',
 '0825',
 '083',
 '0844',
 '08448350055',
 '08448714184',
 '0845',
 '08450542832',
 '08452810071',
 '08452810073',
 '08452810075over18',
 '0870',
 '08700435505150p',
 '08700621170150p',
 '08701237397',
 '08701417012',
 '08701417012150p',
 '0870141701216',
 '08701752560',


In [42]:
v.get_feature_names_out()[3630]
#the differnece between these two line of code is that the code with out at the end provides the component in array where as the 
#the second line of code provides you the componenet in simple show format

'if'

In [38]:
v.vocabulary_

{'if': 3630,
 'bored': 1455,
 'up': 7276,
 'just': 3916,
 'come': 1922,
 'to': 7020,
 'my': 4697,
 'home': 3509,
 'forgot': 2978,
 'tell': 6833,
 'smth': 6340,
 'can': 1647,
 'like': 4151,
 'number': 4890,
 'the': 6894,
 'sections': 6046,
 'so': 6354,
 'that': 6890,
 'it': 3792,
 'clearer': 1860,
 'normally': 4855,
 'use': 7311,
 'drink': 2469,
 'more': 4620,
 'water': 7491,
 'daily': 2163,
 'know': 4003,
 'complain': 1942,
 'num': 4889,
 'only': 4983,
 'bettr': 1356,
 'directly': 2355,
 'go': 3184,
 'bsnl': 1557,
 'offc': 4931,
 'nd': 4747,
 'apply': 1039,
 'for': 2967,
 'do': 2391,
 'noe': 4833,
 'wat': 7484,
 'time': 6985,
 'place': 5271,
 'dat': 2187,
 'sells': 6069,
 '4d': 502,
 'closes': 1872,
 'meeting': 4467,
 'is': 3781,
 'work': 7684,
 'tel': 6829,
 'me': 4448,
 'when': 7572,
 'shall': 6128,
 'tomorrow': 7046,
 'you': 7803,
 'are': 1062,
 'right': 5839,
 'meanwhile': 4456,
 'how': 3558,
 'project': 5497,
 'twins': 7180,
 'comin': 1927,
 'imagine': 3648,
 'finally': 2879,
 'ge

In [44]:
X_train_np=X_train_cv.toarray()
X_train_np[:4][0]

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [51]:
import numpy as np
np.where(X_train_np[1]!=0)


(array([1455, 1922, 3509, 3630, 3916, 4697, 7020, 7276], dtype=int64),)

In [55]:
X_train[:4][4293 ]

'G.W.R'

In [57]:
pip install naive_bayes


  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
     --------------------------------------- 14.9/14.9 MB 18.2 MB/s eta 0:00:00
  Created wheel for naive_bayes: filename=naive_bayes-0.1.1-py3-none-any.whl size=2153 sha256=f6b404515b39c757feedec662d1ba4bb74cfe811892662d53dd4003db333172e
  Stored in directory: c:\users\rashi\appdata\local\pip\cache\wheels\29\fc\1f\44ea7f6ccb226e209a1fa1c4cfd6cddefa75e1691504542ae5
Successfully built naive_bayes
  Attempting uninstall: numpy
    Found existing installation: numpy 1.26.4
    Uninstalling numpy-1.26.4:
      Successfully uninstalled numpy-1.26.4


ERROR: Could not install packages due to an OSError: [WinError 5] Access is denied: 'C:\\Users\\rashi\\anaconda\\Lib\\site-packages\\~umpy.libs\\libopenblas64__v0.3.23-293-gc2f4bdbb-gcc_10_3_0-2bde3a66a51006b2b53eb373ff767a3f.dll'
Consider using the `--user` option or check the permissions.



In [61]:
from sklearn.naive_bayes import MultinomialNB
X_test_cv=v.transform(X_test)
model=MultinomialNB()
model.fit(X_train_cv,y_train)


MultinomialNB()

In [66]:
from sklearn.metrics import classification_report
y_pred=model.predict(X_test_cv)
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.99      0.99      0.99       946
           1       0.97      0.95      0.96       169

    accuracy                           0.99      1115
   macro avg       0.98      0.97      0.98      1115
weighted avg       0.99      0.99      0.99      1115



In [69]:
#if you dont alwasy want to convert the text to numerical you could add all those function to a pipeline using this 
from sklearn.pipeline import Pipeline
clf=Pipeline([
    ("v",CountVectorizer()),
    ("nm",MultinomialNB())
])

In [75]:
clf.fit(X_train,y_train)
y_pred1=clf.predict(X_test)
print(classification_report(y_test,y_pred1))

              precision    recall  f1-score   support

           0       0.99      0.99      0.99       946
           1       0.97      0.95      0.96       169

    accuracy                           0.99      1115
   macro avg       0.98      0.97      0.98      1115
weighted avg       0.99      0.99      0.99      1115



In [77]:
import nltk
nltk.download('wordnet')
nltk.download('omw-1.4')

from nltk.corpus import wordnet as wn

# Define the words
word1 = "dog"
word2 = "cat"

# Find the first synset for each word
synset1 = wn.synsets(word1)[0]
synset2 = wn.synsets(word2)[0]

# Print the synsets
print(f"Synset of {word1}: {synset1}")
print(f"Synset of {word2}: {synset2}")

# Calculate path similarity
path_similarity = synset1.path_similarity(synset2)
print(f"Path similarity between {word1} and {word2}: {path_similarity}")

# Calculate Wu-Palmer similarity
wup_similarity = synset1.wup_similarity(synset2)
print(f"Wu-Palmer similarity between {word1} and {word2}: {wup_similarity}")


[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\rashi\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package omw-1.4 to
[nltk_data]     C:\Users\rashi\AppData\Roaming\nltk_data...
[nltk_data]   Package omw-1.4 is already up-to-date!


Synset of dog: [Synset('dog.n.01'), Synset('frump.n.01'), Synset('dog.n.03'), Synset('cad.n.01'), Synset('frank.n.02'), Synset('pawl.n.01'), Synset('andiron.n.01'), Synset('chase.v.01')]
Synset of cat: [Synset('cat.n.01'), Synset('guy.n.01'), Synset('cat.n.03'), Synset('kat.n.01'), Synset('cat-o'-nine-tails.n.01'), Synset('caterpillar.n.02'), Synset('big_cat.n.01'), Synset('computerized_tomography.n.01'), Synset('cat.v.01'), Synset('vomit.v.01')]


AttributeError: 'list' object has no attribute 'path_similarity'

In [2]:
import nltk
from nltk.corpus import wordnet

# Ensure you have the necessary resources
# nltk.download('wordnet')

# Select a word to analyze
word = "car"

# Get all synsets for the word
synsets = wordnet.synsets(word)

# Display relationships for each synset
for synset in synsets:
    print(f"Synset: {synset.name()}")
    print(f"Definition: {synset.definition()}")
    
    # Hypernyms
    hypernyms = synset.hypernyms()
    if hypernyms:
        print("\tHypernyms:")
        for hypernym in hypernyms:
            print(f"\t\t{hypernym.name()} - {hypernym.definition()}")
    
    # Hyponyms
    hyponyms = synset.hyponyms()
    if hyponyms:
        print("\tHyponyms:")
        for hyponym in hyponyms:
            print(f"\t\t{hyponym.name()} - {hyponym.definition()}")
    
    # Holonyms
    holonyms = synset.member_holonyms() + synset.part_holonyms() + synset.substance_holonyms()
    if holonyms:
        print("\tHolonyms:")
        for holonym in holonyms:
            print(f"\t\t{holonym.name()} - {holonym.definition()}")
    
    # Meronyms
    meronyms = synset.member_meronyms() + synset.part_meronyms() + synset.substance_meronyms()
    if meronyms:
        print("\tMeronyms:")
        for meronym in meronyms:
            print(f"\t\t{meronym.name()} - {meronym.definition()}")
    
    print("\n")


Synset: car.n.01
Definition: a motor vehicle with four wheels; usually propelled by an internal combustion engine
	Hypernyms:
		motor_vehicle.n.01 - a self-propelled wheeled vehicle that does not run on rails
	Hyponyms:
		ambulance.n.01 - a vehicle that takes people to and from hospitals
		beach_wagon.n.01 - a car that has a long body and rear door with space behind rear seat
		bus.n.04 - a car that is old and unreliable
		cab.n.03 - a car driven by a person whose job is to take passengers where they want to go in exchange for money
		compact.n.03 - a small and economical car
		convertible.n.01 - a car that has top that can be folded or removed
		coupe.n.01 - a car with two doors and front seats and a luggage compartment
		cruiser.n.01 - a car in which policemen cruise the streets; equipped with radiotelephonic communications to headquarters
		electric.n.01 - a car that is powered by electricity
		gas_guzzler.n.01 - a car with relatively low fuel efficiency
		hardtop.n.01 - a car that 